In [3]:
import tensorflow as tf
import numpy as np

In [37]:
## Training Data
x_train = [[1,2,1], [1,3,2], [1,3,4], [1,5,5], [1,7,5], [1,2,5], [1,6,6], [1,7,7]]
y_train = [[0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,6], [1,0,0]]

In [38]:
## Evaluation Model

x_test = [[2,1,1], [3,1,2], [3,3,4]]
y_test = [[0,0,1], [0,0,1], [0,0,1]]

In [39]:
print(x_test)
print(y_test)

[[2, 1, 1], [3, 1, 2], [3, 3, 4]]
[[0, 0, 1], [0, 0, 1], [0, 0, 1]]


In [40]:
## Assign Variables 

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [41]:
hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [42]:
## Correnct Prediction Test Model

prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [43]:
# Launch graph

with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    for step in range(201): 
        cost_val, W_val, _ = sess.run([cost, W, optimizer], 
                                     feed_dict = {X: x_train, Y: y_train})
        print(step, cost_val, W_val)

    print("Prediction:", sess.run(prediction, feed_dict = {X: x_test}))
    print("Accuracy:", sess.run(accuracy, feed_dict = {X: x_test}))

0 5.670203 [[ 0.92011034  1.4769454   1.7483612 ]
 [ 0.7019692   1.2674932   1.5170476 ]
 [-2.044698   -0.08969346 -0.81451076]]
1 5.6266756 [[ 0.9436215   1.3756992   1.8260963 ]
 [ 0.8613281   0.7069414   1.9182405 ]
 [-1.8838676  -0.6535692  -0.41146535]]
2 6.891539 [[ 0.96763945  1.412762    1.7650155 ]
 [ 1.0217813   0.8809436   1.5837852 ]
 [-1.7224516  -0.46710104 -0.7593496 ]]
3 3.4065466 [[ 0.98797816  1.4399254   1.7175134 ]
 [ 1.1736224   1.0188208   1.2940669 ]
 [-1.5666009  -0.32647642 -1.0558248 ]]
4 3.3197155 [[ 0.9985966   1.347685    1.7991354 ]
 [ 1.2941852   0.49461138  1.6977136 ]
 [-1.4356209  -0.8578861  -0.65539515]]
5 4.6677475 [[ 1.0151092   1.384801    1.7455068 ]
 [ 1.4354199   0.66871107  1.3823792 ]
 [-1.2887208  -0.671464   -0.98871726]]
6 2.5018258 [[ 0.95173377  1.4167274   1.7769557 ]
 [ 1.1658843   0.8235204   1.4971055 ]
 [-1.5483886  -0.5107331  -0.88978034]]
7 2.4811354 [[ 0.96618265  1.439127    1.7401073 ]
 [ 1.2992542   0.9386863   1.2485697 ]
 [

147 3.5787086 [[-0.02846378  1.8462433   2.327637  ]
 [ 1.179664    0.88129115  1.4255549 ]
 [-1.1989076  -0.37554306 -1.37445   ]]
148 2.7346272 [[-0.00841961  1.7624995   2.3913367 ]
 [ 1.3207908   0.4136149   1.7521044 ]
 [-1.0561097  -0.85697675 -1.0358142 ]]
149 3.8673854 [[ 0.01335681  1.799215    2.3328447 ]
 [ 1.4715662   0.58679086  1.4281529 ]
 [-0.90630895 -0.67233545 -1.3702562 ]]
150 2.5461953 [[-0.07194026  1.8262907   2.391066  ]
 [ 1.0209758   0.72756547  1.7379688 ]
 [-1.354857   -0.5323314  -1.0617121 ]]
151 3.5741374 [[-0.04742802  1.8563423   2.3365023 ]
 [ 1.1822134   0.8801695   1.4241271 ]
 [-1.1934927  -0.37867278 -1.3767352 ]]
152 2.7286217 [[-0.02735082  1.7726084   2.4001591 ]
 [ 1.3232957   0.41264975  1.7505646 ]
 [-1.05078    -0.85993505 -1.0381856 ]]
153 3.8609898 [[-0.00554348  1.8093219   2.3416383 ]
 [ 1.4740866   0.5858209   1.4266024 ]
 [-0.9009778  -0.67529887 -1.372624  ]]
154 2.55119 [[-0.09094796  1.8363724   2.3999922 ]
 [ 1.0220144   0.7266185 

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_5' with dtype float and shape [?,3]
	 [[Node: Placeholder_5 = Placeholder[dtype=DT_FLOAT, shape=[?,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder_5', defined at:
  File "D:\Anaconda4\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda4\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\DataStudy\venv2\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "D:\DataStudy\venv2\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\DataStudy\venv2\lib\site-packages\ipykernel\kernelapp.py", line 497, in start
    self.io_loop.start()
  File "D:\DataStudy\venv2\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "D:\Anaconda4\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "D:\Anaconda4\lib\asyncio\base_events.py", line 1432, in _run_once
    handle._run()
  File "D:\Anaconda4\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "D:\DataStudy\venv2\lib\site-packages\tornado\platform\asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "D:\DataStudy\venv2\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\DataStudy\venv2\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "D:\DataStudy\venv2\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "D:\DataStudy\venv2\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "D:\DataStudy\venv2\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\DataStudy\venv2\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "D:\DataStudy\venv2\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\DataStudy\venv2\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "D:\DataStudy\venv2\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\DataStudy\venv2\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\DataStudy\venv2\lib\site-packages\IPython\core\interactiveshell.py", line 2705, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\DataStudy\venv2\lib\site-packages\IPython\core\interactiveshell.py", line 2809, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\DataStudy\venv2\lib\site-packages\IPython\core\interactiveshell.py", line 2869, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-40-f33b26e059d5>", line 4, in <module>
    Y = tf.placeholder("float", [None, 3])
  File "D:\DataStudy\venv2\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1735, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "D:\DataStudy\venv2\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 5928, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "D:\DataStudy\venv2\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\DataStudy\venv2\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "D:\DataStudy\venv2\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "D:\DataStudy\venv2\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder_5' with dtype float and shape [?,3]
	 [[Node: Placeholder_5 = Placeholder[dtype=DT_FLOAT, shape=[?,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
