In [3]:
import tensorflow as tf
import numpy as np

In [37]:
## Training Data
x_train = [[1,2,1], [1,3,2], [1,3,4], [1,5,5], [1,7,5], [1,2,5], [1,6,6], [1,7,7]]
y_train = [[0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,6], [1,0,0]]

In [38]:
## Evaluation Model

x_test = [[2,1,1], [3,1,2], [3,3,4]]
y_test = [[0,0,1], [0,0,1], [0,0,1]]

In [39]:
print(x_test)
print(y_test)

[[2, 1, 1], [3, 1, 2], [3, 3, 4]]
[[0, 0, 1], [0, 0, 1], [0, 0, 1]]


In [40]:
## Assign Variables 

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [41]:
hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [42]:
## Correnct Prediction Test Model

prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [43]:
# Launch graph

with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    for step in range(201): 
        cost_val, W_val, _ = sess.run([cost, W, optimizer], 
                                     feed_dict = {X: x_train, Y: y_train})
        print(step, cost_val, W_val)

    print("Prediction:", sess.run(prediction, feed_dict = {X: x_test}))
    print("Accuracy:", sess.run(accuracy, feed_dict = {X: x_test}))

0 5.670203 [[ 0.92011034  1.4769454   1.7483612 ]
 [ 0.7019692   1.2674932   1.5170476 ]
 [-2.044698   -0.08969346 -0.81451076]]
1 5.6266756 [[ 0.9436215   1.3756992   1.8260963 ]
 [ 0.8613281   0.7069414   1.9182405 ]
 [-1.8838676  -0.6535692  -0.41146535]]
2 6.891539 [[ 0.96763945  1.412762    1.7650155 ]
 [ 1.0217813   0.8809436   1.5837852 ]
 [-1.7224516  -0.46710104 -0.7593496 ]]
3 3.4065466 [[ 0.98797816  1.4399254   1.7175134 ]
 [ 1.1736224   1.0188208   1.2940669 ]
 [-1.5666009  -0.32647642 -1.0558248 ]]
4 3.3197155 [[ 0.9985966   1.347685    1.7991354 ]
 [ 1.2941852   0.49461138  1.6977136 ]
 [-1.4356209  -0.8578861  -0.65539515]]
5 4.6677475 [[ 1.0151092   1.384801    1.7455068 ]
 [ 1.4354199   0.66871107  1.3823792 ]
 [-1.2887208  -0.671464   -0.98871726]]
6 2.5018258 [[ 0.95173377  1.4167274   1.7769557 ]
 [ 1.1658843   0.8235204   1.4971055 ]
 [-1.5483886  -0.5107331  -0.88978034]]
7 2.4811354 [[ 0.96618265  1.439127    1.7401073 ]
 [ 1.2992542   0.9386863   1.2485697 ]
 [

147 3.5787086 [[-0.02846378  1.8462433   2.327637  ]
 [ 1.179664    0.88129115  1.4255549 ]
 [-1.1989076  -0.37554306 -1.37445   ]]
148 2.7346272 [[-0.00841961  1.7624995   2.3913367 ]
 [ 1.3207908   0.4136149   1.7521044 ]
 [-1.0561097  -0.85697675 -1.0358142 ]]
149 3.8673854 [[ 0.01335681  1.799215    2.3328447 ]
 [ 1.4715662   0.58679086  1.4281529 ]
 [-0.90630895 -0.67233545 -1.3702562 ]]
150 2.5461953 [[-0.07194026  1.8262907   2.391066  ]
 [ 1.0209758   0.72756547  1.7379688 ]
 [-1.354857   -0.5323314  -1.0617121 ]]
151 3.5741374 [[-0.04742802  1.8563423   2.3365023 ]
 [ 1.1822134   0.8801695   1.4241271 ]
 [-1.1934927  -0.37867278 -1.3767352 ]]
152 2.7286217 [[-0.02735082  1.7726084   2.4001591 ]
 [ 1.3232957   0.41264975  1.7505646 ]
 [-1.05078    -0.85993505 -1.0381856 ]]
153 3.8609898 [[-0.00554348  1.8093219   2.3416383 ]
 [ 1.4740866   0.5858209   1.4266024 ]
 [-0.9009778  -0.67529887 -1.372624  ]]
154 2.55119 [[-0.09094796  1.8363724   2.3999922 ]
 [ 1.0220144   0.7266185 

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_5' with dtype float and shape [?,3]
	 [[Node: Placeholder_5 = Placeholder[dtype=DT_FLOAT, shape=[?,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder_5', defined at:
  File "D:\Anaconda4\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda4\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\DataStudy\venv2\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "D:\DataStudy\venv2\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\DataStudy\venv2\lib\site-packages\ipykernel\kernelapp.py", line 497, in start
    self.io_loop.start()
  File "D:\DataStudy\venv2\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "D:\Anaconda4\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "D:\Anaconda4\lib\asyncio\base_events.py", line 1432, in _run_once
    handle._run()
  File "D:\Anaconda4\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "D:\DataStudy\venv2\lib\site-packages\tornado\platform\asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "D:\DataStudy\venv2\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\DataStudy\venv2\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "D:\DataStudy\venv2\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "D:\DataStudy\venv2\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "D:\DataStudy\venv2\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\DataStudy\venv2\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "D:\DataStudy\venv2\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\DataStudy\venv2\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "D:\DataStudy\venv2\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\DataStudy\venv2\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\DataStudy\venv2\lib\site-packages\IPython\core\interactiveshell.py", line 2705, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\DataStudy\venv2\lib\site-packages\IPython\core\interactiveshell.py", line 2809, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\DataStudy\venv2\lib\site-packages\IPython\core\interactiveshell.py", line 2869, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-40-f33b26e059d5>", line 4, in <module>
    Y = tf.placeholder("float", [None, 3])
  File "D:\DataStudy\venv2\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1735, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "D:\DataStudy\venv2\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 5928, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "D:\DataStudy\venv2\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\DataStudy\venv2\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "D:\DataStudy\venv2\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "D:\DataStudy\venv2\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder_5' with dtype float and shape [?,3]
	 [[Node: Placeholder_5 = Placeholder[dtype=DT_FLOAT, shape=[?,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


## Non-normalized inputs

### Non-normalized input is likely to show the poor outcome, since the model is not able to optimize.

In [6]:
## Data

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
              [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
              [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
              [816, 820.958984, 1008100, 815.48999, 819.23999],
              [819.359985, 823, 1188100, 818.469971, 818.97998],
              [819, 823, 1198100, 816, 820.450012],
              [811.700012, 815.25, 1098100, 809.780029, 813.669983],
              [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

array([[831.659973],
       [828.070007],
       [824.159973],
       [819.23999 ],
       [818.97998 ],
       [820.450012],
       [813.669983],
       [809.559998]])

In [7]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [9]:
hypothesis = tf.matmul(X,W)+ b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [11]:
## Minimize

optimizer=tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [13]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001): 
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction\n", hy_val)

0 Cost:  17630888.0 
Prediction
 [[-2755.498 ]
 [-4352.728 ]
 [-3667.8281]
 [-2912.0957]
 [-3230.587 ]
 [-3246.2961]
 [-3062.0586]
 [-3581.2505]]
1 Cost:  1.91777e+22 
Prediction
 [[9.76853811e+10]
 [1.96650680e+11]
 [1.54697990e+11]
 [1.08442485e+11]
 [1.27805260e+11]
 [1.28880968e+11]
 [1.18123872e+11]
 [1.50395159e+11]]
2 Cost:  2.1070166e+37 
Prediction
 [[-3.2379136e+18]
 [-6.5182524e+18]
 [-5.1276742e+18]
 [-3.5944723e+18]
 [-4.2362776e+18]
 [-4.2719334e+18]
 [-3.9153749e+18]
 [-4.9850505e+18]]
3 Cost:  inf 
Prediction
 [[1.0732503e+26]
 [2.1605629e+26]
 [1.6996369e+26]
 [1.1914364e+26]
 [1.4041715e+26]
 [1.4159901e+26]
 [1.2978039e+26]
 [1.6523623e+26]]
4 Cost:  inf 
Prediction
 [[-3.5574327e+33]
 [-7.1614769e+33]
 [-5.6336751e+33]
 [-3.9491767e+33]
 [-4.6543157e+33]
 [-4.6934900e+33]
 [-4.3017460e+33]
 [-5.4769779e+33]]
5 Cost:  inf 
Prediction
 [[inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]]
6 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [

162 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
163 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
164 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
165 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
166 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
167 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
168 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
169 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
170 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
171 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
172 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
173 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [

337 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
338 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
339 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
340 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
341 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
342 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
343 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
344 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
345 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
346 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
347 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
348 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [

492 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
493 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
494 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
495 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
496 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
497 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
498 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
499 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
500 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
501 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
502 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
503 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [

675 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
676 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
677 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
678 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
679 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
680 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
681 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
682 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
683 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
684 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
685 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
686 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [

775 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
776 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
777 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
778 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
779 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
780 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
781 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
782 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
783 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
784 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
785 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
786 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [

875 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
876 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
877 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
878 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
879 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
880 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
881 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
882 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
883 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
884 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
885 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
886 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [

975 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
976 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
977 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
978 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
979 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
980 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
981 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
982 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
983 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
984 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
985 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
986 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [

1075 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1076 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1077 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1078 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1079 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1080 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1081 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1082 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1083 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1084 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1085 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1086 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [na

 [nan]]
1175 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1176 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1177 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1178 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1179 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1180 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1181 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1182 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1183 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1184 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1185 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1186 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [n

 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1275 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1276 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1277 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1278 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1279 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1280 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1281 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1282 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1283 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1284 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1285 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [na

 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1375 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1376 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1377 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1378 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1379 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1380 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1381 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1382 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1383 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1384 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1385 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [na

1474 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1475 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1476 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1477 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1478 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1479 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1480 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1481 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1482 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1483 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1484 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1485 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [na

1574 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1575 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1576 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1577 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1578 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1579 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1580 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1581 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1582 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1583 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1584 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1585 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [na

1674 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1675 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1676 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1677 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1678 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1679 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1680 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1681 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1682 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1683 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1684 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1685 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [na

1774 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1775 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1776 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1777 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1778 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1779 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1780 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1781 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1782 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1783 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1784 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1785 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [na

1893 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1894 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1895 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1896 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1897 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1898 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1899 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1900 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1901 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1902 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1903 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1904 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [na

## Normize Data with MinMaxScaler



In [23]:
from sklearn.preprocessing import MinMaxScaler

## Scaler from sklearn.

scaler = MinMaxScaler()
xy = scaler.fit_transform(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X,W)+ b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

## Minimize

optimizer=tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001): 
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction\n", hy_val)

0 Cost:  1.8630738 
Prediction
 [[-1.130513  ]
 [-1.6827998 ]
 [-0.8335046 ]
 [ 0.05977964]
 [-0.39973897]
 [-0.42975944]
 [ 0.50797236]
 [ 0.0286386 ]]
1 Cost:  1.8629644 
Prediction
 [[-1.1304505 ]
 [-1.68274   ]
 [-0.8334556 ]
 [ 0.05981642]
 [-0.3996945 ]
 [-0.42971665]
 [ 0.507999  ]
 [ 0.02866459]]
2 Cost:  1.8628551 
Prediction
 [[-1.130388  ]
 [-1.6826804 ]
 [-0.8334066 ]
 [ 0.0598532 ]
 [-0.39964992]
 [-0.42967385]
 [ 0.50802565]
 [ 0.02869064]]
3 Cost:  1.8627453 
Prediction
 [[-1.1303253 ]
 [-1.6826205 ]
 [-0.83335775]
 [ 0.05988997]
 [-0.39960545]
 [-0.42963094]
 [ 0.5080523 ]
 [ 0.02871662]]
4 Cost:  1.862636 
Prediction
 [[-1.1302629 ]
 [-1.6825607 ]
 [-0.83330876]
 [ 0.05992681]
 [-0.39956087]
 [-0.42958802]
 [ 0.50807893]
 [ 0.02874261]]
5 Cost:  1.8625264 
Prediction
 [[-1.1302004 ]
 [-1.6825008 ]
 [-0.83325976]
 [ 0.05996346]
 [-0.39951617]
 [-0.42954534]
 [ 0.5081056 ]
 [ 0.0287686 ]]
6 Cost:  1.8624167 
Prediction
 [[-1.1301377 ]
 [-1.682441  ]
 [-0.83321077]
 [ 0.0

130 Cost:  1.848907 
Prediction
 [[-1.1224034 ]
 [-1.6750438 ]
 [-0.8271537 ]
 [ 0.06454712]
 [-0.3939625 ]
 [-0.42420197]
 [ 0.51142955]
 [ 0.032013  ]]
131 Cost:  1.8487984 
Prediction
 [[-1.1223412 ]
 [-1.6749843 ]
 [-0.8271049 ]
 [ 0.06458372]
 [-0.39391828]
 [-0.4241594 ]
 [ 0.51145613]
 [ 0.03203887]]
132 Cost:  1.84869 
Prediction
 [[-1.1222789 ]
 [-1.6749249 ]
 [-0.82705617]
 [ 0.06462032]
 [-0.39387393]
 [-0.4241166 ]
 [ 0.5114826 ]
 [ 0.03206474]]
133 Cost:  1.8485818 
Prediction
 [[-1.1222168 ]
 [-1.6748656 ]
 [-0.8270074 ]
 [ 0.06465685]
 [-0.39382958]
 [-0.42407393]
 [ 0.51150906]
 [ 0.03209066]]
134 Cost:  1.8484731 
Prediction
 [[-1.1221546 ]
 [-1.6748056 ]
 [-0.8269588 ]
 [ 0.06469345]
 [-0.39378536]
 [-0.42403138]
 [ 0.51153564]
 [ 0.03211653]]
135 Cost:  1.8483648 
Prediction
 [[-1.1220924 ]
 [-1.6747464 ]
 [-0.82691014]
 [ 0.06472999]
 [-0.393741  ]
 [-0.42398882]
 [ 0.5115621 ]
 [ 0.03214234]]
136 Cost:  1.8482563 
Prediction
 [[-1.1220301 ]
 [-1.6746867 ]
 [-0.8268

222 Cost:  1.8389621 
Prediction
 [[-1.1166886 ]
 [-1.6695749 ]
 [-0.82267654]
 [ 0.06790626]
 [-0.3898915 ]
 [-0.4202851 ]
 [ 0.5138653 ]
 [ 0.0343914 ]]
223 Cost:  1.8388543 
Prediction
 [[-1.1166265 ]
 [-1.6695154 ]
 [-0.8226281 ]
 [ 0.06794274]
 [-0.38984746]
 [-0.4202426 ]
 [ 0.5138917 ]
 [ 0.03441721]]
224 Cost:  1.8387463 
Prediction
 [[-1.1165644 ]
 [-1.669456  ]
 [-0.8225795 ]
 [ 0.06797922]
 [-0.38980317]
 [-0.42020023]
 [ 0.51391816]
 [ 0.03444302]]
225 Cost:  1.838639 
Prediction
 [[-1.1165025 ]
 [-1.6693966 ]
 [-0.8225309 ]
 [ 0.06801564]
 [-0.389759  ]
 [-0.4201576 ]
 [ 0.51394457]
 [ 0.03446889]]
226 Cost:  1.8385313 
Prediction
 [[-1.1164405 ]
 [-1.6693374 ]
 [-0.82248235]
 [ 0.06805211]
 [-0.38971484]
 [-0.4201151 ]
 [ 0.513971  ]
 [ 0.0344947 ]]
227 Cost:  1.838423 
Prediction
 [[-1.1163783 ]
 [-1.6692777 ]
 [-0.82243365]
 [ 0.06808853]
 [-0.38967067]
 [-0.42007262]
 [ 0.51399744]
 [ 0.03452045]]
228 Cost:  1.8383157 
Prediction
 [[-1.1163166 ]
 [-1.6692185 ]
 [-0.822

285 Cost:  1.8321859 
Prediction
 [[-1.1127834 ]
 [-1.6658368 ]
 [-0.81961745]
 [ 0.0702008 ]
 [-0.38711017]
 [-0.41760916]
 [ 0.51552844]
 [ 0.03601611]]
286 Cost:  1.8320785 
Prediction
 [[-1.1127214 ]
 [-1.6657777 ]
 [-0.81956893]
 [ 0.0702371 ]
 [-0.38706607]
 [-0.41756672]
 [ 0.5155548 ]
 [ 0.03604186]]
287 Cost:  1.8319714 
Prediction
 [[-1.1126595 ]
 [-1.6657183 ]
 [-0.8195204 ]
 [ 0.07027346]
 [-0.38702208]
 [-0.41752428]
 [ 0.5155812 ]
 [ 0.03606761]]
288 Cost:  1.8318639 
Prediction
 [[-1.1125975 ]
 [-1.665659  ]
 [-0.819472  ]
 [ 0.07030982]
 [-0.38697785]
 [-0.41748184]
 [ 0.51560754]
 [ 0.03609329]]
289 Cost:  1.8317571 
Prediction
 [[-1.1125357 ]
 [-1.6656001 ]
 [-0.8194234 ]
 [ 0.0703463 ]
 [-0.38693386]
 [-0.4174394 ]
 [ 0.5156339 ]
 [ 0.0361191 ]]
290 Cost:  1.8316495 
Prediction
 [[-1.1124737 ]
 [-1.6655405 ]
 [-0.819375  ]
 [ 0.07038265]
 [-0.38688976]
 [-0.41739696]
 [ 0.5156603 ]
 [ 0.03614485]]
291 Cost:  1.8315421 
Prediction
 [[-1.1124117 ]
 [-1.6654813 ]
 [-0.8

400 Cost:  1.8199115 
Prediction
 [[-1.1056834 ]
 [-1.6590457 ]
 [-0.8140578 ]
 [ 0.07437241]
 [-0.38205433]
 [-0.41274488]
 [ 0.5185522 ]
 [ 0.03896767]]
401 Cost:  1.8198054 
Prediction
 [[-1.1056219 ]
 [-1.6589867 ]
 [-0.81400967]
 [ 0.07440865]
 [-0.38201046]
 [-0.41270268]
 [ 0.51857835]
 [ 0.03899318]]
402 Cost:  1.8196992 
Prediction
 [[-1.1055603 ]
 [-1.6589277 ]
 [-0.8139614 ]
 [ 0.07444477]
 [-0.3819666 ]
 [-0.4126606 ]
 [ 0.5186045 ]
 [ 0.03901875]]
403 Cost:  1.8195928 
Prediction
 [[-1.1054987 ]
 [-1.6588689 ]
 [-0.8139132 ]
 [ 0.07448101]
 [-0.38192272]
 [-0.41261828]
 [ 0.51863074]
 [ 0.03904438]]
404 Cost:  1.8194869 
Prediction
 [[-1.1054372 ]
 [-1.6588099 ]
 [-0.81386495]
 [ 0.07451707]
 [-0.38187885]
 [-0.4125762 ]
 [ 0.51865697]
 [ 0.03906989]]
405 Cost:  1.8193805 
Prediction
 [[-1.1053756 ]
 [-1.6587511 ]
 [-0.81381667]
 [ 0.07455325]
 [-0.3818351 ]
 [-0.412534  ]
 [ 0.51868314]
 [ 0.03909546]]
406 Cost:  1.8192744 
Prediction
 [[-1.105314  ]
 [-1.6586924 ]
 [-0.8

453 Cost:  1.8142915 
Prediction
 [[-1.1024219 ]
 [-1.6559263 ]
 [-0.8115045 ]
 [ 0.07628822]
 [-0.37973225]
 [-0.41051114]
 [ 0.5199404 ]
 [ 0.04032248]]
454 Cost:  1.8141859 
Prediction
 [[-1.1023606 ]
 [-1.6558678 ]
 [-0.8114562 ]
 [ 0.0763244 ]
 [-0.3796885 ]
 [-0.41046882]
 [ 0.5199666 ]
 [ 0.04034805]]
455 Cost:  1.8140799 
Prediction
 [[-1.1022991 ]
 [-1.6558088 ]
 [-0.81140816]
 [ 0.07636046]
 [-0.37964463]
 [-0.41042674]
 [ 0.51999277]
 [ 0.04037362]]
456 Cost:  1.8139741 
Prediction
 [[-1.1022376 ]
 [-1.65575   ]
 [-0.8113599 ]
 [ 0.07639658]
 [-0.37960088]
 [-0.41038465]
 [ 0.52001894]
 [ 0.04039919]]
457 Cost:  1.8138683 
Prediction
 [[-1.1021763 ]
 [-1.655691  ]
 [-0.81131196]
 [ 0.0764327 ]
 [-0.37955713]
 [-0.41034245]
 [ 0.5200451 ]
 [ 0.0404247 ]]
458 Cost:  1.8137624 
Prediction
 [[-1.1021147 ]
 [-1.6556325 ]
 [-0.8112637 ]
 [ 0.07646888]
 [-0.37951326]
 [-0.41030037]
 [ 0.52007127]
 [ 0.04045027]]
459 Cost:  1.8136566 
Prediction
 [[-1.1020532 ]
 [-1.6555735 ]
 [-0.8

 [ 0.04256731]]
542 Cost:  1.8048973 
Prediction
 [[-1.0969561 ]
 [-1.6506976 ]
 [-0.807225  ]
 [ 0.07949799]
 [-0.37584126]
 [-0.4067675 ]
 [ 0.52226555]
 [ 0.04259276]]
543 Cost:  1.8047923 
Prediction
 [[-1.0968947 ]
 [-1.6506392 ]
 [-0.80717707]
 [ 0.07953393]
 [-0.37579763]
 [-0.40672553]
 [ 0.52229166]
 [ 0.04261816]]
544 Cost:  1.804687 
Prediction
 [[-1.0968333 ]
 [-1.6505805 ]
 [-0.807129  ]
 [ 0.07957   ]
 [-0.37575388]
 [-0.40668344]
 [ 0.5223177 ]
 [ 0.04264361]]
545 Cost:  1.8045819 
Prediction
 [[-1.0967722 ]
 [-1.6505219 ]
 [-0.8070811 ]
 [ 0.07960594]
 [-0.37571025]
 [-0.4066416 ]
 [ 0.52234375]
 [ 0.04266906]]
546 Cost:  1.8044765 
Prediction
 [[-1.0967108 ]
 [-1.650463  ]
 [-0.80703306]
 [ 0.079642  ]
 [-0.37566674]
 [-0.40659964]
 [ 0.52236986]
 [ 0.04269457]]
547 Cost:  1.8043712 
Prediction
 [[-1.0966494 ]
 [-1.6504043 ]
 [-0.806985  ]
 [ 0.07967794]
 [-0.375623  ]
 [-0.40655756]
 [ 0.52239585]
 [ 0.04271996]]
548 Cost:  1.804266 
Prediction
 [[-1.096588  ]
 [-1.65

640 Cost:  1.7946265 
Prediction
 [[-1.0909607 ]
 [-1.6449594 ]
 [-0.8025295 ]
 [ 0.08301842]
 [-0.37157255]
 [-0.4026609 ]
 [ 0.52481604]
 [ 0.04508376]]
641 Cost:  1.794522 
Prediction
 [[-1.0908996 ]
 [-1.6449009 ]
 [-0.8024818 ]
 [ 0.08305436]
 [-0.3715291 ]
 [-0.402619  ]
 [ 0.52484196]
 [ 0.04510909]]
642 Cost:  1.7944177 
Prediction
 [[-1.0908387 ]
 [-1.6448424 ]
 [-0.8024339 ]
 [ 0.08309019]
 [-0.37148565]
 [-0.4025771 ]
 [ 0.52486795]
 [ 0.04513448]]
643 Cost:  1.7943132 
Prediction
 [[-1.0907776 ]
 [-1.644784  ]
 [-0.80238605]
 [ 0.08312607]
 [-0.3714422 ]
 [-0.40253532]
 [ 0.52489394]
 [ 0.04515988]]
644 Cost:  1.794209 
Prediction
 [[-1.0907166 ]
 [-1.6447256 ]
 [-0.8023383 ]
 [ 0.08316195]
 [-0.37139875]
 [-0.40249354]
 [ 0.5249199 ]
 [ 0.04518527]]
645 Cost:  1.7941043 
Prediction
 [[-1.0906554 ]
 [-1.644667  ]
 [-0.80229044]
 [ 0.08319771]
 [-0.37135518]
 [-0.40245175]
 [ 0.5249459 ]
 [ 0.0452106 ]]
646 Cost:  1.7940004 
Prediction
 [[-1.0905945 ]
 [-1.6446087 ]
 [-0.802

712 Cost:  1.7871325 
Prediction
 [[-1.086571  ]
 [-1.6407602 ]
 [-0.79909295]
 [ 0.08559579]
 [-0.36844784]
 [-0.3996548 ]
 [ 0.5266829 ]
 [ 0.04690605]]
713 Cost:  1.7870288 
Prediction
 [[-1.0865102 ]
 [-1.6407022 ]
 [-0.7990454 ]
 [ 0.08563155]
 [-0.36840457]
 [-0.39961296]
 [ 0.5267088 ]
 [ 0.04693133]]
714 Cost:  1.7869252 
Prediction
 [[-1.0864494 ]
 [-1.6406438 ]
 [-0.7989976 ]
 [ 0.08566725]
 [-0.3683613 ]
 [-0.39957136]
 [ 0.5267347 ]
 [ 0.0469566 ]]
715 Cost:  1.7868214 
Prediction
 [[-1.0863883 ]
 [-1.6405859 ]
 [-0.79895   ]
 [ 0.08570296]
 [-0.3683179 ]
 [-0.39952964]
 [ 0.5267606 ]
 [ 0.04698187]]
716 Cost:  1.7867177 
Prediction
 [[-1.0863276 ]
 [-1.6405275 ]
 [-0.79890233]
 [ 0.08573872]
 [-0.36827463]
 [-0.39948803]
 [ 0.52678645]
 [ 0.04700714]]
717 Cost:  1.7866141 
Prediction
 [[-1.0862668 ]
 [-1.6404696 ]
 [-0.79885477]
 [ 0.08577448]
 [-0.36823136]
 [-0.39944643]
 [ 0.5268123 ]
 [ 0.04703236]]
718 Cost:  1.7865102 
Prediction
 [[-1.0862057 ]
 [-1.6404111 ]
 [-0.7

841 Cost:  1.7738016 
Prediction
 [[-1.0787296 ]
 [-1.6332637 ]
 [-0.7929578 ]
 [ 0.09019685]
 [-0.36286926]
 [-0.39428794]
 [ 0.5300134 ]
 [ 0.05015653]]
842 Cost:  1.7736988 
Prediction
 [[-1.0786691 ]
 [-1.6332058 ]
 [-0.79291034]
 [ 0.09023249]
 [-0.36282623]
 [-0.39424658]
 [ 0.5300391 ]
 [ 0.05018169]]
843 Cost:  1.7735959 
Prediction
 [[-1.0786084 ]
 [-1.6331476 ]
 [-0.7928629 ]
 [ 0.09026802]
 [-0.36278307]
 [-0.3942051 ]
 [ 0.5300648 ]
 [ 0.05020678]]
844 Cost:  1.7734933 
Prediction
 [[-1.0785478 ]
 [-1.6330899 ]
 [-0.7928153 ]
 [ 0.09030366]
 [-0.36273992]
 [-0.3941636 ]
 [ 0.5300906 ]
 [ 0.05023193]]
845 Cost:  1.77339 
Prediction
 [[-1.078487  ]
 [-1.6330317 ]
 [-0.7927679 ]
 [ 0.09033918]
 [-0.36269677]
 [-0.394122  ]
 [ 0.5301163 ]
 [ 0.05025703]]
846 Cost:  1.7732873 
Prediction
 [[-1.0784265 ]
 [-1.6329738 ]
 [-0.79272056]
 [ 0.09037477]
 [-0.3626535 ]
 [-0.39408052]
 [ 0.53014207]
 [ 0.05028218]]
847 Cost:  1.7731845 
Prediction
 [[-1.0783657 ]
 [-1.6329156 ]
 [-0.792

939 Cost:  1.7637606 
Prediction
 [[-1.0728005 ]
 [-1.627591  ]
 [-0.78831637]
 [ 0.09367615]
 [-0.35864985]
 [-0.390229  ]
 [ 0.53253233]
 [ 0.05261582]]
940 Cost:  1.7636584 
Prediction
 [[-1.0727401 ]
 [-1.6275334 ]
 [-0.7882691 ]
 [ 0.09371156]
 [-0.35860687]
 [-0.39018756]
 [ 0.532558  ]
 [ 0.05264086]]
941 Cost:  1.7635565 
Prediction
 [[-1.0726798 ]
 [-1.6274755 ]
 [-0.78822196]
 [ 0.09374696]
 [-0.35856402]
 [-0.39014626]
 [ 0.5325837 ]
 [ 0.05266595]]
942 Cost:  1.7634546 
Prediction
 [[-1.0726197 ]
 [-1.6274178 ]
 [-0.78817445]
 [ 0.09378242]
 [-0.35852104]
 [-0.39010507]
 [ 0.53260934]
 [ 0.05269098]]
943 Cost:  1.7633526 
Prediction
 [[-1.0725592 ]
 [-1.6273602 ]
 [-0.7881274 ]
 [ 0.09381783]
 [-0.35847807]
 [-0.39006364]
 [ 0.532635  ]
 [ 0.05271602]]
944 Cost:  1.7632506 
Prediction
 [[-1.0724988 ]
 [-1.6273024 ]
 [-0.78808016]
 [ 0.09385324]
 [-0.3584351 ]
 [-0.39002234]
 [ 0.53266066]
 [ 0.05274111]]
945 Cost:  1.7631483 
Prediction
 [[-1.0724386 ]
 [-1.6272445 ]
 [-0.7

993 Cost:  1.7582599 
Prediction
 [[-1.0695441 ]
 [-1.624474  ]
 [-0.7857664 ]
 [ 0.09558719]
 [-0.356332  ]
 [-0.38799912]
 [ 0.533916  ]
 [ 0.05396718]]
994 Cost:  1.7581582 
Prediction
 [[-1.0694838 ]
 [-1.6244161 ]
 [-0.7857191 ]
 [ 0.09562254]
 [-0.3562891 ]
 [-0.38795787]
 [ 0.53394157]
 [ 0.05399215]]
995 Cost:  1.7580564 
Prediction
 [[-1.0694234 ]
 [-1.6243584 ]
 [-0.7856719 ]
 [ 0.09565789]
 [-0.35624617]
 [-0.38791662]
 [ 0.53396714]
 [ 0.05401713]]
996 Cost:  1.7579548 
Prediction
 [[-1.0693631 ]
 [-1.6243007 ]
 [-0.7856247 ]
 [ 0.09569323]
 [-0.35620338]
 [-0.38787538]
 [ 0.53399277]
 [ 0.05404216]]
997 Cost:  1.7578529 
Prediction
 [[-1.0693028 ]
 [-1.624243  ]
 [-0.7855775 ]
 [ 0.09572858]
 [-0.35616046]
 [-0.38783413]
 [ 0.5340184 ]
 [ 0.05406713]]
998 Cost:  1.7577511 
Prediction
 [[-1.0692427 ]
 [-1.6241851 ]
 [-0.7855304 ]
 [ 0.09576398]
 [-0.35611755]
 [-0.3877929 ]
 [ 0.53404397]
 [ 0.05409223]]
999 Cost:  1.7576498 
Prediction
 [[-1.0691824 ]
 [-1.6241276 ]
 [-0.7

1130 Cost:  1.7444 
Prediction
 [[-1.0613029 ]
 [-1.6165955 ]
 [-0.7793203 ]
 [ 0.1004191 ]
 [-0.35047168]
 [-0.3823616 ]
 [ 0.5374112 ]
 [ 0.05737853]]
1131 Cost:  1.7442995 
Prediction
 [[-1.0612428 ]
 [-1.6165383 ]
 [-0.77927333]
 [ 0.10045433]
 [-0.350429  ]
 [-0.38232058]
 [ 0.53743666]
 [ 0.05740339]]
1132 Cost:  1.7441988 
Prediction
 [[-1.061183  ]
 [-1.6164808 ]
 [-0.7792266 ]
 [ 0.1004895 ]
 [-0.35038632]
 [-0.38227946]
 [ 0.5374621 ]
 [ 0.05742818]]
1133 Cost:  1.7440984 
Prediction
 [[-1.0611231 ]
 [-1.6164236 ]
 [-0.77917975]
 [ 0.10052472]
 [-0.35034364]
 [-0.38223833]
 [ 0.5374875 ]
 [ 0.05745298]]
1134 Cost:  1.7439973 
Prediction
 [[-1.0610628 ]
 [-1.6163659 ]
 [-0.7791328 ]
 [ 0.10055989]
 [-0.35030097]
 [-0.38219732]
 [ 0.53751296]
 [ 0.05747783]]
1135 Cost:  1.743897 
Prediction
 [[-1.0610027 ]
 [-1.6163089 ]
 [-0.7790858 ]
 [ 0.10059506]
 [-0.3502583 ]
 [-0.3821563 ]
 [ 0.5375384 ]
 [ 0.05750263]]
1136 Cost:  1.7437962 
Prediction
 [[-1.0609429 ]
 [-1.6162512 ]
 [-

1193 Cost:  1.7380769 
Prediction
 [[-1.0575296 ]
 [-1.6129875 ]
 [-0.7763685 ]
 [ 0.10263181]
 [-0.34778798]
 [-0.37977993]
 [ 0.5390121 ]
 [ 0.05894065]]
1194 Cost:  1.7379769 
Prediction
 [[-1.0574698 ]
 [-1.6129303 ]
 [-0.7763216 ]
 [ 0.10266691]
 [-0.34774548]
 [-0.379739  ]
 [ 0.5390374 ]
 [ 0.05896538]]
1195 Cost:  1.7378771 
Prediction
 [[-1.05741   ]
 [-1.6128734 ]
 [-0.77627504]
 [ 0.10270196]
 [-0.34770286]
 [-0.37969804]
 [ 0.5390628 ]
 [ 0.05899012]]
1196 Cost:  1.737777 
Prediction
 [[-1.0573502 ]
 [-1.6128161 ]
 [-0.77622813]
 [ 0.10273701]
 [-0.34766036]
 [-0.3796572 ]
 [ 0.53908813]
 [ 0.05901486]]
1197 Cost:  1.7376769 
Prediction
 [[-1.0572903 ]
 [-1.6127589 ]
 [-0.7761812 ]
 [ 0.102772  ]
 [-0.34761775]
 [-0.37961626]
 [ 0.5391135 ]
 [ 0.05903959]]
1198 Cost:  1.7375768 
Prediction
 [[-1.0572305 ]
 [-1.6127017 ]
 [-0.77613455]
 [ 0.1028071 ]
 [-0.34757525]
 [-0.37957555]
 [ 0.53913885]
 [ 0.05906439]]
1199 Cost:  1.7374771 
Prediction
 [[-1.057171  ]
 [-1.6126448 ]


1255 Cost:  1.7318845 
Prediction
 [[-1.0538261 ]
 [-1.6094449 ]
 [-0.7734702 ]
 [ 0.10480374]
 [-0.3451534 ]
 [-0.3772456 ]
 [ 0.5405835 ]
 [ 0.06047463]]
1256 Cost:  1.7317848 
Prediction
 [[-1.0537665 ]
 [-1.6093879 ]
 [-0.77342373]
 [ 0.10483873]
 [-0.34511095]
 [-0.37720484]
 [ 0.54060876]
 [ 0.06049931]]
1257 Cost:  1.7316852 
Prediction
 [[-1.0537066 ]
 [-1.6093309 ]
 [-0.7733769 ]
 [ 0.10487372]
 [-0.3450685 ]
 [-0.37716407]
 [ 0.5406341 ]
 [ 0.06052399]]
1258 Cost:  1.7315857 
Prediction
 [[-1.0536473 ]
 [-1.6092739 ]
 [-0.7733304 ]
 [ 0.10490865]
 [-0.3450262 ]
 [-0.3771233 ]
 [ 0.5406594 ]
 [ 0.06054872]]
1259 Cost:  1.7314858 
Prediction
 [[-1.0535874 ]
 [-1.6092165 ]
 [-0.77328354]
 [ 0.10494369]
 [-0.34498364]
 [-0.3770824 ]
 [ 0.5406847 ]
 [ 0.0605734 ]]
1260 Cost:  1.7313864 
Prediction
 [[-1.0535278 ]
 [-1.6091597 ]
 [-0.77323693]
 [ 0.10497862]
 [-0.3449412 ]
 [-0.37704152]
 [ 0.54071   ]
 [ 0.06059808]]
1261 Cost:  1.7312865 
Prediction
 [[-1.053468  ]
 [-1.6091025 ]

1331 Cost:  1.7243258 
Prediction
 [[-1.049294  ]
 [-1.605109  ]
 [-0.76992416]
 [ 0.10746008]
 [-0.3419304 ]
 [-0.37414527]
 [ 0.5425046 ]
 [ 0.06235045]]
1332 Cost:  1.724227 
Prediction
 [[-1.0492346 ]
 [-1.6050522 ]
 [-0.7698776 ]
 [ 0.10749495]
 [-0.34188813]
 [-0.37410456]
 [ 0.5425298 ]
 [ 0.06237507]]
1333 Cost:  1.7241275 
Prediction
 [[-1.0491749 ]
 [-1.6049951 ]
 [-0.7698312 ]
 [ 0.10752988]
 [-0.34184587]
 [-0.37406385]
 [ 0.54255503]
 [ 0.06239974]]
1334 Cost:  1.7240285 
Prediction
 [[-1.0491152 ]
 [-1.6049383 ]
 [-0.7697844 ]
 [ 0.10756475]
 [-0.3418035 ]
 [-0.37402302]
 [ 0.54258025]
 [ 0.06242436]]
1335 Cost:  1.7239296 
Prediction
 [[-1.0490558 ]
 [-1.6048815 ]
 [-0.76973796]
 [ 0.10759962]
 [-0.34176123]
 [-0.37398243]
 [ 0.5426055 ]
 [ 0.06244898]]
1336 Cost:  1.7238303 
Prediction
 [[-1.0489964 ]
 [-1.6048243 ]
 [-0.76969117]
 [ 0.10763448]
 [-0.34171885]
 [-0.37394172]
 [ 0.5426307 ]
 [ 0.0624736 ]]
1337 Cost:  1.7237308 
Prediction
 [[-1.0489368 ]
 [-1.6047672 ]


1403 Cost:  1.7172039 
Prediction
 [[-1.0450113 ]
 [-1.6010125 ]
 [-0.7665737 ]
 [ 0.10996956]
 [-0.3388855 ]
 [-0.37121612]
 [ 0.5443188 ]
 [ 0.0641222 ]]
1404 Cost:  1.7171049 
Prediction
 [[-1.0449519 ]
 [-1.6009555 ]
 [-0.76652724]
 [ 0.11000437]
 [-0.3388433 ]
 [-0.37117547]
 [ 0.54434395]
 [ 0.0641467 ]]
1405 Cost:  1.7170063 
Prediction
 [[-1.0448923 ]
 [-1.6008987 ]
 [-0.766481  ]
 [ 0.11003917]
 [-0.33880097]
 [-0.37113494]
 [ 0.5443691 ]
 [ 0.06417125]]
1406 Cost:  1.7169077 
Prediction
 [[-1.044833  ]
 [-1.600842  ]
 [-0.7664346 ]
 [ 0.11007398]
 [-0.33875877]
 [-0.3710943 ]
 [ 0.54439425]
 [ 0.06419575]]
1407 Cost:  1.7168095 
Prediction
 [[-1.0447736 ]
 [-1.6007855 ]
 [-0.766388  ]
 [ 0.11010873]
 [-0.33871657]
 [-0.37105376]
 [ 0.54441935]
 [ 0.06422025]]
1408 Cost:  1.7167106 
Prediction
 [[-1.0447142 ]
 [-1.6007285 ]
 [-0.7663416 ]
 [ 0.1101436 ]
 [-0.3386745 ]
 [-0.3710131 ]
 [ 0.54444444]
 [ 0.06424475]]
1409 Cost:  1.7166123 
Prediction
 [[-1.0446546 ]
 [-1.600672  ]

1540 Cost:  1.7037735 
Prediction
 [[-1.0369    ]
 [-1.5932602 ]
 [-0.76023185]
 [ 0.11472219]
 [-0.33311987]
 [-0.3656702 ]
 [ 0.5477545 ]
 [ 0.06747389]]
1541 Cost:  1.7036756 
Prediction
 [[-1.0368409 ]
 [-1.5932035 ]
 [-0.7601856 ]
 [ 0.11475676]
 [-0.3330779 ]
 [-0.3656299 ]
 [ 0.5477795 ]
 [ 0.06749827]]
1542 Cost:  1.7035782 
Prediction
 [[-1.0367818 ]
 [-1.5931472 ]
 [-0.76013935]
 [ 0.11479133]
 [-0.33303607]
 [-0.3655895 ]
 [ 0.5478045 ]
 [ 0.06752264]]
1543 Cost:  1.7034807 
Prediction
 [[-1.0367229 ]
 [-1.5930905 ]
 [-0.76009345]
 [ 0.11482596]
 [-0.33299398]
 [-0.3655492 ]
 [ 0.54782945]
 [ 0.06754702]]
1544 Cost:  1.7033834 
Prediction
 [[-1.0366639 ]
 [-1.5930341 ]
 [-0.7600472 ]
 [ 0.11486048]
 [-0.33295202]
 [-0.3655089 ]
 [ 0.5478544 ]
 [ 0.0675714 ]]
1545 Cost:  1.7032858 
Prediction
 [[-1.0366048 ]
 [-1.592978  ]
 [-0.76000094]
 [ 0.11489505]
 [-0.33291006]
 [-0.36546838]
 [ 0.54787946]
 [ 0.06759578]]
1546 Cost:  1.7031884 
Prediction
 [[-1.0365459 ]
 [-1.5929216 ]

1640 Cost:  1.6940498 
Prediction
 [[-1.0310025 ]
 [-1.5876207 ]
 [-0.75562024]
 [ 0.11817598]
 [-0.32892847]
 [-0.36163843]
 [ 0.55025023]
 [ 0.06991005]]
1641 Cost:  1.6939529 
Prediction
 [[-1.0309436 ]
 [-1.5875645 ]
 [-0.75557405]
 [ 0.11821049]
 [-0.3288867 ]
 [-0.3615983 ]
 [ 0.5502751 ]
 [ 0.06993437]]
1642 Cost:  1.693856 
Prediction
 [[-1.0308845 ]
 [-1.5875081 ]
 [-0.7555281 ]
 [ 0.11824501]
 [-0.3288448 ]
 [-0.36155796]
 [ 0.5503    ]
 [ 0.06995869]]
1643 Cost:  1.6937591 
Prediction
 [[-1.0308256 ]
 [-1.5874517 ]
 [-0.755482  ]
 [ 0.11827952]
 [-0.32880288]
 [-0.36151773]
 [ 0.550325  ]
 [ 0.06998307]]
1644 Cost:  1.6936624 
Prediction
 [[-1.030767  ]
 [-1.5873954 ]
 [-0.7554358 ]
 [ 0.11831391]
 [-0.3287611 ]
 [-0.3614775 ]
 [ 0.55034983]
 [ 0.07000732]]
1645 Cost:  1.6935656 
Prediction
 [[-1.0307081 ]
 [-1.5873394 ]
 [-0.75538987]
 [ 0.11834842]
 [-0.3287192 ]
 [-0.36143726]
 [ 0.55037475]
 [ 0.0700317 ]]
1646 Cost:  1.6934686 
Prediction
 [[-1.030649  ]
 [-1.587283  ]


1740 Cost:  1.6843944 
Prediction
 [[-1.0251255 ]
 [-1.5819981 ]
 [-0.75102323]
 [ 0.12161738]
 [-0.32475132]
 [-0.35762042]
 [ 0.5527369 ]
 [ 0.07233834]]
1741 Cost:  1.6842985 
Prediction
 [[-1.0250669 ]
 [-1.5819423 ]
 [-0.75097746]
 [ 0.12165171]
 [-0.3247097 ]
 [-0.35758036]
 [ 0.5527617 ]
 [ 0.0723626 ]]
1742 Cost:  1.6842022 
Prediction
 [[-1.0250084 ]
 [-1.5818863 ]
 [-0.75093156]
 [ 0.12168604]
 [-0.324668  ]
 [-0.3575402 ]
 [ 0.5527865 ]
 [ 0.0723868 ]]
1743 Cost:  1.6841059 
Prediction
 [[-1.0249498 ]
 [-1.58183   ]
 [-0.7508858 ]
 [ 0.12172037]
 [-0.32462627]
 [-0.35750026]
 [ 0.5528114 ]
 [ 0.07241106]]
1744 Cost:  1.68401 
Prediction
 [[-1.0248911 ]
 [-1.581774  ]
 [-0.75084   ]
 [ 0.12175471]
 [-0.32458454]
 [-0.3574602 ]
 [ 0.5528362 ]
 [ 0.07243532]]
1745 Cost:  1.683914 
Prediction
 [[-1.0248327 ]
 [-1.581718  ]
 [-0.750794  ]
 [ 0.12178904]
 [-0.32454306]
 [-0.35742003]
 [ 0.55286103]
 [ 0.07245958]]
1746 Cost:  1.6838181 
Prediction
 [[-1.0247741 ]
 [-1.5816619 ]
 [

1840 Cost:  1.6748228 
Prediction
 [[-1.0192742 ]
 [-1.5764067 ]
 [-0.7464502 ]
 [ 0.12504303]
 [-0.3205942 ]
 [-0.35362196]
 [ 0.55521137]
 [ 0.07475209]]
1841 Cost:  1.6747276 
Prediction
 [[-1.019216  ]
 [-1.576351  ]
 [-0.7464045 ]
 [ 0.12507719]
 [-0.32055283]
 [-0.35358214]
 [ 0.55523604]
 [ 0.07477617]]
1842 Cost:  1.6746322 
Prediction
 [[-1.0191574 ]
 [-1.5762951 ]
 [-0.7463589 ]
 [ 0.12511146]
 [-0.32051122]
 [-0.3535422 ]
 [ 0.5552607 ]
 [ 0.07480025]]
1843 Cost:  1.6745365 
Prediction
 [[-1.0190989 ]
 [-1.5762392 ]
 [-0.7463132 ]
 [ 0.12514555]
 [-0.32046974]
 [-0.35350215]
 [ 0.5552854 ]
 [ 0.07482433]]
1844 Cost:  1.6744413 
Prediction
 [[-1.0190405 ]
 [-1.5761836 ]
 [-0.74626756]
 [ 0.12517977]
 [-0.32042813]
 [-0.35346234]
 [ 0.5553101 ]
 [ 0.07484841]]
1845 Cost:  1.6743457 
Prediction
 [[-1.0189819 ]
 [-1.5761276 ]
 [-0.7462218 ]
 [ 0.12521398]
 [-0.32038677]
 [-0.3534224 ]
 [ 0.55533475]
 [ 0.07487243]]
1846 Cost:  1.6742506 
Prediction
 [[-1.0189236 ]
 [-1.576072  ]

1940 Cost:  1.6653168 
Prediction
 [[-1.0134411 ]
 [-1.5708323 ]
 [-0.7418918 ]
 [ 0.1284563 ]
 [-0.31645137]
 [-0.3496371 ]
 [ 0.5576756 ]
 [ 0.07715672]]
1941 Cost:  1.6652224 
Prediction
 [[-1.0133829 ]
 [-1.5707767 ]
 [-0.74184644]
 [ 0.12849033]
 [-0.31641006]
 [-0.34959733]
 [ 0.55770016]
 [ 0.07718074]]
1942 Cost:  1.6651275 
Prediction
 [[-1.0133245 ]
 [-1.5707209 ]
 [-0.74180084]
 [ 0.12852442]
 [-0.31636864]
 [-0.34955746]
 [ 0.5577248 ]
 [ 0.07720476]]
1943 Cost:  1.6650327 
Prediction
 [[-1.0132664 ]
 [-1.5706652 ]
 [-0.74175525]
 [ 0.12855846]
 [-0.3163272 ]
 [-0.3495177 ]
 [ 0.5577494 ]
 [ 0.07722878]]
1944 Cost:  1.6649377 
Prediction
 [[-1.0132079 ]
 [-1.5706093 ]
 [-0.74170965]
 [ 0.12859261]
 [-0.3162859 ]
 [-0.34947783]
 [ 0.557774  ]
 [ 0.07725281]]
1945 Cost:  1.664843 
Prediction
 [[-1.0131499 ]
 [-1.5705538 ]
 [-0.74166405]
 [ 0.12862664]
 [-0.31624436]
 [-0.34943807]
 [ 0.5577986 ]
 [ 0.07727683]]
1946 Cost:  1.6647487 
Prediction
 [[-1.0130916 ]
 [-1.5704982 ]
